import boardJson from '../data/board.json';
import type { BoardFile, BoardRow } from './types';

/**
 * Read the board generated by the daily build.
 *
 * Statically imported so Vercel bundles it — API routes must never touch the
 * filesystem or call gametools at request time.
 */
export function getBoard(): BoardFile {
  return boardJson as unknown as BoardFile;
}

export function getMeta() {
  return getBoard().meta;
}

export function getUnresolved() {
  return getBoard().unresolved;
}

export function getSeason(
  season?: string,
): { season: string; ranked: BoardRow[]; provisional: BoardRow[] } | null {
  const board = getBoard();
  const key = season ?? board.meta.currentSeason;
  const ranked = board.seasons[key];
  if (!ranked) return null;
  return { season: key, ranked, provisional: board.provisional[key] ?? [] };
}
