import boardJson from '../data/board.json';
import type { BoardFile, BoardRow } from './types';

/**
 * Read the board generated by the daily build.
 *
 * Statically imported so Vercel bundles it — API routes must never touch the
 * filesystem or call gametools at request time.
 */
export function getBoard(): BoardFile {
  return boardJson as unknown as BoardFile;
}

export function getMeta() {
  return getBoard().meta;
}

export function getUnresolved() {
  return getBoard().unresolved;
}

/**
 * The spec documents `?season=<n>` (e.g. `?season=4`), but board keys are
 * `SeasonN`. Normalise a purely numeric value; anything else (including an
 * already-correct `SeasonN`, or garbage that will 404) passes through as-is.
 */
function normalizeSeasonKey(season: string): string {
  return /^\d+$/.test(season) ? `Season${season}` : season;
}

export function getSeason(
  season?: string,
): { season: string; ranked: BoardRow[]; provisional: BoardRow[] } | null {
  const board = getBoard();
  const key = season === undefined ? board.meta.currentSeason : normalizeSeasonKey(season);
  const ranked = board.seasons[key];
  if (!ranked) return null;
  return { season: key, ranked, provisional: board.provisional[key] ?? [] };
}
